EEEEEEEEEE
======================================================================
ERROR: test_console (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/local/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_console
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/AirBnB_clone_v3/tests/test_console.py", line 5, in <module>
    import MySQLdb
ImportError: No module named 'MySQLdb'


======================================================================
ERROR: test_models.test_amenity (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/local/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_models.test_amenity
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/AirBnB_clone_v3/tests/test_models/test_amenity.py", line 5, in <module>
    from tests.test_models.test_base_model import TestBasemodel
  File "/AirBnB_clone_v3/tests/__init__.py", line 5, in <module>
    from typing import TextIO
ImportError: No module named 'typing'


======================================================================
ERROR: test_models.test_base_model (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/local/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_models.test_base_model
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/AirBnB_clone_v3/tests/test_models/test_base_model.py", line 9, in <module>
    from models.base_model import BaseModel, Base
  File "/AirBnB_clone_v3/models/__init__.py", line 5, in <module>
    from models.engine.db_storage import DBStorage
  File "/AirBnB_clone_v3/models/engine/db_storage.py", line 4, in <module>
    from sqlalchemy import create_engine
ImportError: No module named 'sqlalchemy'


======================================================================
ERROR: test_models.test_city (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/local/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_models.test_city
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/AirBnB_clone_v3/tests/test_models/test_city.py", line 5, in <module>
    from models.city import City
  File "/AirBnB_clone_v3/models/__init__.py", line 5, in <module>
    from models.engine.db_storage import DBStorage
  File "/AirBnB_clone_v3/models/engine/db_storage.py", line 4, in <module>
    from sqlalchemy import create_engine
ImportError: No module named 'sqlalchemy'


======================================================================
ERROR: test_models.test_engine.test_db_storage (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/local/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_models.test_engine.test_db_storage
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/AirBnB_clone_v3/tests/test_models/test_engine/test_db_storage.py", line 3, in <module>
    import MySQLdb
ImportError: No module named 'MySQLdb'


======================================================================
ERROR: test_models.test_engine.test_file_storage (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/local/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_models.test_engine.test_file_storage
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/AirBnB_clone_v3/tests/test_models/test_engine/test_file_storage.py", line 6, in <module>
    from models import storage
  File "/AirBnB_clone_v3/models/__init__.py", line 5, in <module>
    from models.engine.db_storage import DBStorage
  File "/AirBnB_clone_v3/models/engine/db_storage.py", line 4, in <module>
    from sqlalchemy import create_engine
ImportError: No module named 'sqlalchemy'


======================================================================
ERROR: test_models.test_place (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/local/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_models.test_place
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/AirBnB_clone_v3/tests/test_models/test_place.py", line 5, in <module>
    from tests.test_models.test_base_model import TestBasemodel
  File "/AirBnB_clone_v3/tests/__init__.py", line 5, in <module>
    from typing import TextIO
ImportError: No module named 'typing'


======================================================================
ERROR: test_models.test_review (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/local/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_models.test_review
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/AirBnB_clone_v3/tests/test_models/test_review.py", line 5, in <module>
    from tests.test_models.test_base_model import TestBasemodel
  File "/AirBnB_clone_v3/tests/__init__.py", line 5, in <module>
    from typing import TextIO
ImportError: No module named 'typing'


======================================================================
ERROR: test_models.test_state (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/local/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_models.test_state
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/AirBnB_clone_v3/tests/test_models/test_state.py", line 5, in <module>
    from tests.test_models.test_base_model import TestBasemodel
  File "/AirBnB_clone_v3/tests/__init__.py", line 5, in <module>
    from typing import TextIO
ImportError: No module named 'typing'


======================================================================
ERROR: test_models.test_user (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/usr/local/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_models.test_user
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/AirBnB_clone_v3/tests/test_models/test_user.py", line 4, in <module>
    from sqlalchemy import Column
ImportError: No module named 'sqlalchemy'


----------------------------------------------------------------------
Ran 10 tests in 0.001s

FAILED (errors=10)
